In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

**Task 1: Creating New Features**

1. Identify at least 2 existing columns from your dataset.
2. Create new meaningful features, examples:
   - Price per unit
   - Total value = quantity × price
   - Age group from age
   - Revenue category from revenue
3. Add the newly created features to the DataFrame.

dataset can be found at https://www.kaggle.com/datasets/abbas829/e-commerce-sales-analytics-dataset

In [28]:
df = pd.read_csv('ecommerce_sales_analytics_5000.csv')
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [29]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='str')

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), str(4)
memory usage: 593.2 KB

In [31]:
df['order_date'] = pd.to_datetime(df['order_date'])
df.dtypes

order_id                     int64
order_date          datetime64[us]
customer_id                  int64
product_category               str
region                         str
quantity                     int64
unit_price                 float64
discount                   float64
payment_method                 str
delivery_days                int64
customer_rating            float64
revenue                    float64
dtype: object

In [32]:
# feature engineering
df['total_value'] = df['quantity'] * df['unit_price']
df['delivery_date'] = df['order_date'] + pd.to_timedelta(df['delivery_days'], unit='D')

In [33]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_value,delivery_date
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55,2022-01-11
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18,2022-01-08
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84,2022-01-09
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35,2022-01-10
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35,2022-01-09

**Task 2: Handling Date & Text Features (If Available)**
- If your dataset has:
    - Date column → extract year, month, day
    - Text column → extract length of text or word count
- If not available, explain briefly why this step was skipped.

In [34]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day'] = df['order_date'].dt.day
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_value,delivery_date,order_year,order_month,order_day
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55,2022-01-11,2022,1,1
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18,2022-01-08,2022,1,2
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84,2022-01-09,2022,1,3
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35,2022-01-10,2022,1,4
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35,2022-01-09,2022,1,5

In [35]:
df['category_length'] = df['product_category'].apply(len)
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_value,delivery_date,order_year,order_month,order_day,category_length
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55,2022-01-11,2022,1,1,6
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18,2022-01-08,2022,1,2,8
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84,2022-01-09,2022,1,3,6
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35,2022-01-10,2022,1,4,11
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35,2022-01-09,2022,1,5,8

## PART 2 — Feature Encoding

**Task 3: One-Hot Encoding**

1. Identify categorical columns.
2. Apply One-Hot Encoding using:
   - pd.get_dummies() (for understanding)
3. Display the transformed DataFrame.

In [36]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue', 'total_value', 'delivery_date',
       'order_year', 'order_month', 'order_day', 'category_length'],
      dtype='str')

In [37]:
# categorical columns
categorical_columns = [col for col in df.columns if df[col].dtype == 'str']
categorical_columns

['product_category', 'region', 'payment_method']

In [38]:
df_ohe = pd.get_dummies(df[categorical_columns], dtype=int)
df_ohe.head()

,product_category_Beauty,product_category_Clothing,product_category_Electronics,product_category_Home,region_East,region_North,region_South,region_West,payment_method_COD,payment_method_Card,payment_method_Wallet
0,1,0,0,0,0,0,1,0,0,0,1
1,0,1,0,0,0,0,1,0,0,1,0
2,1,0,0,0,1,0,0,0,1,0,0
3,0,0,1,0,0,0,0,1,0,0,1
4,0,1,0,0,0,0,0,1,0,0,1

In [39]:
df_ohe.columns

Index(['product_category_Beauty', 'product_category_Clothing',
       'product_category_Electronics', 'product_category_Home', 'region_East',
       'region_North', 'region_South', 'region_West', 'payment_method_COD',
       'payment_method_Card', 'payment_method_Wallet'],
      dtype='str')

**Task 4: ColumnTransformer (Recommended Way)**

1. Separate:
   - Numerical features
   - Categorical features
2. Use ColumnTransformer to:
   - Apply OneHotEncoder to categorical columns
   - Pass numerical columns unchanged
3. Fit and transform the dataset.

In [ ]:
# dropping order_id as it is not a feature
df = df.drop(["order_id"],axis=1)
df.head()

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_value,delivery_date,order_year,order_month,order_day,category_length
0,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55,2022-01-11,2022,1,1,6
1,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18,2022-01-08,2022,1,2,8
2,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84,2022-01-09,2022,1,3,6
3,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35,2022-01-10,2022,1,4,11
4,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35,2022-01-09,2022,1,5,8

In [52]:
categorical_columns = [col for col in df.columns if df[col].dtype == 'str']
numerical_columns = ['quantity', 'unit_price', 'discount', 'delivery_days', 'customer_rating',]

print("Categorical columns: ", categorical_columns)
print("Numerical columns: ", numerical_columns)

Categorical columns:  ['product_category', 'region', 'payment_method']
Numerical columns:  ['quantity', 'unit_price', 'discount', 'delivery_days', 'customer_rating']

In [53]:

ct = ColumnTransformer(
    [
        ('ohe', OneHotEncoder(), categorical_columns),  
    ],
    remainder='passthrough'
)
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe', OneHotEncoder(),
                                 ['product_category', 'region',
                                  'payment_method'])])

In [54]:
df_transformed = ct.fit_transform(df)
df_transformed

array([[1.0, 0.0, 0.0, ..., 1, 1, 6],
       [0.0, 1.0, 0.0, ..., 1, 2, 8],
       [1.0, 0.0, 0.0, ..., 1, 3, 6],
       ...,
       [1.0, 0.0, 0.0, ..., 9, 7, 6],
       [0.0, 0.0, 1.0, ..., 9, 8, 11],
       [0.0, 0.0, 0.0, ..., 9, 9, 4]], shape=(5000, 25), dtype=object)

In [55]:
column_names = ct.get_feature_names_out()
column_names

array(['ohe__product_category_Beauty', 'ohe__product_category_Clothing',
       'ohe__product_category_Electronics', 'ohe__product_category_Home',
       'ohe__region_East', 'ohe__region_North', 'ohe__region_South',
       'ohe__region_West', 'ohe__payment_method_COD',
       'ohe__payment_method_Card', 'ohe__payment_method_Wallet',
       'remainder__order_date', 'remainder__customer_id',
       'remainder__quantity', 'remainder__unit_price',
       'remainder__discount', 'remainder__delivery_days',
       'remainder__customer_rating', 'remainder__revenue',
       'remainder__total_value', 'remainder__delivery_date',
       'remainder__order_year', 'remainder__order_month',
       'remainder__order_day', 'remainder__category_length'], dtype=object)

In [56]:
df_transformed = pd.DataFrame(df_transformed, columns=column_names)
df_transformed.head()

,ohe__product_category_Beauty,ohe__product_category_Clothing,ohe__product_category_Electronics,ohe__product_category_Home,ohe__region_East,ohe__region_North,ohe__region_South,ohe__region_West,ohe__payment_method_COD,ohe__payment_method_Card,...,remainder__discount,remainder__delivery_days,remainder__customer_rating,remainder__revenue,remainder__total_value,remainder__delivery_date,remainder__order_year,remainder__order_month,remainder__order_day,remainder__category_length
0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.28,10,4.7,1883.2,2615.55,2022-01-11,2022,1,1,6
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.09,6,3.9,304.1,334.18,2022-01-08,2022,1,2,8
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.31,6,2.5,644.35,933.84,2022-01-09,2022,1,3,6
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.02,6,1.6,2569.9,2622.35,2022-01-10,2022,1,4,11
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.33,4,4.9,468.56,699.35,2022-01-09,2022,1,5,8

## PART 3 — Feature Scaling

**Task 5: Standardization (StandardScaler)**

1. Apply StandardScaler on numerical features.
2. Explain:
   - Mean becomes ~0
   - Standard deviation becomes ~1

In [60]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df[numerical_columns])
df_scaled

array([[ 1.46282817,  0.38543066,  0.9864125 ,  1.23097461,  1.49102472],
       [ 1.46282817, -1.54026833, -0.88747143, -0.03767901,  0.79994363],
       [-0.51717747,  0.01690608,  1.28228891, -0.03767901, -0.40944827],
       ...,
       [-0.51717747, -1.36608035,  0.59191062, -0.03767901,  0.36801795],
       [-0.02217606, -1.00452801,  0.29603421, -0.67200582, -0.15029286],
       [ 1.46282817, -0.45401598,  1.57816532, -0.35484242,  0.79994363]],
      shape=(5000, 5))

In [61]:
df_scaled = pd.DataFrame(df_scaled, columns=numerical_columns)
df_scaled.head()

   quantity  unit_price  discount  delivery_days  customer_rating
0  1.462828    0.385431  0.986412       1.230975         1.491025
1  1.462828   -1.540268 -0.887471      -0.037679         0.799944
2 -0.517177    0.016906  1.282289      -0.037679        -0.409448
3  0.472825    1.276578 -1.577850      -0.037679        -1.186914
4  0.472825   -0.995901  1.479540      -0.672006         1.663795

In [62]:
df_scaled.describe()

,quantity,unit_price,discount,delivery_days,customer_rating
count,5.000000e+03,5.000000e+03,5.000000e+03,5.000000e+03,5.000000e+03
mean,-2.241762e-16,-2.486900e-16,-1.350031e-17,-7.425172e-17,-4.348522e-16
std,1.000100e+00,1.000100e+00,1.000100e+00,1.000100e+00,1.000100e+00
min,-1.507180e+00,-1.732832e+00,-1.775101e+00,-1.623496e+00,-1.705225e+00
25%,-1.012179e+00,-8.657626e-01,-8.874714e-01,-9.891692e-01,-8.413739e-01
50%,-2.217606e-02,8.693009e-03,1.578008e-04,-3.767901e-02,2.247741e-02
75%,9.678268e-01,8.693961e-01,8.877870e-01,9.138112e-01,8.863288e-01
max,1.462828e+00,1.722625e+00,1.676791e+00,1.548138e+00,1.750180e+00

mean is 0 and std is 1

**Task 6: Normalization (MinMaxScaler)**

1. Apply MinMaxScaler on numerical features.
2. Show values scaled between 0 and 1.
3. Compare output with StandardScaler.

In [63]:
from sklearn.preprocessing import MinMaxScaler
mx_scaler = MinMaxScaler()
df_scaled = mx_scaler.fit_transform(df[numerical_columns])
df_scaled

array([[1.        , 0.61301961, 0.8       , 0.9       , 0.925     ],
       [1.        , 0.0557275 , 0.25714286, 0.5       , 0.725     ],
       [0.33333333, 0.50636959, 0.88571429, 0.5       , 0.375     ],
       ...,
       [0.33333333, 0.10613704, 0.68571429, 0.5       , 0.6       ],
       [0.5       , 0.21076931, 0.6       , 0.3       , 0.45      ],
       [1.        , 0.37008601, 0.97142857, 0.4       , 0.725     ]],
      shape=(5000, 5))

In [64]:
df_scaled = pd.DataFrame(df_scaled, columns=numerical_columns)
df_scaled.head()

   quantity  unit_price  discount  delivery_days  customer_rating
0  1.000000    0.613020  0.800000            0.9            0.925
1  1.000000    0.055728  0.257143            0.5            0.725
2  0.333333    0.506370  0.885714            0.5            0.375
3  0.666667    0.870915  0.057143            0.5            0.150
4  0.666667    0.213266  0.942857            0.3            0.975

In [65]:
df_scaled.describe()

          quantity   unit_price     discount  delivery_days  customer_rating
count  5000.000000  5000.000000  5000.000000    5000.000000      5000.000000
mean      0.507467     0.501477     0.514240       0.511880         0.493495
std       0.336733     0.289426     0.289725       0.315326         0.289431
min       0.000000     0.000000     0.000000       0.000000         0.000000
25%       0.166667     0.250928     0.257143       0.200000         0.250000
50%       0.500000     0.503993     0.514286       0.500000         0.500000
75%       0.833333     0.753078     0.771429       0.800000         0.750000
max       1.000000     1.000000     1.000000       1.000000         1.000000

all the values are between 0 and 1

## PART 4 — Building ML Pipeline

**Task 7: Create a Preprocessing Pipeline**

1. Create separate pipelines:
   - Numerical pipeline → Scaling
   - Categorical pipeline → OneHotEncoding
2. Combine them using ColumnTransformer.

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [67]:
numerical_pipeline = Pipeline([
    ('scaler', StandardScaler())
])
categorical_pipeline = Pipeline([
    ('ohe', OneHotEncoder())
])

pipeline = ColumnTransformer([
    ('num_pipeline', numerical_pipeline, numerical_columns),
    ('cat_pipeline', categorical_pipeline, categorical_columns)
])
pipeline

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['quantity', 'unit_price', 'discount',
                                  'delivery_days', 'customer_rating']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('ohe', OneHotEncoder())]),
                                 ['product_category', 'region',
                                  'payment_method'])])

In [68]:
df_transformed_pipeline = pipeline.fit_transform(df)
df_transformed_pipeline

array([[ 1.46282817,  0.38543066,  0.9864125 , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.46282817, -1.54026833, -0.88747143, ...,  0.        ,
         1.        ,  0.        ],
       [-0.51717747,  0.01690608,  1.28228891, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.51717747, -1.36608035,  0.59191062, ...,  0.        ,
         0.        ,  1.        ],
       [-0.02217606, -1.00452801,  0.29603421, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.46282817, -0.45401598,  1.57816532, ...,  1.        ,
         0.        ,  0.        ]], shape=(5000, 16))

In [69]:
column_names = pipeline.get_feature_names_out()
column_names

array(['num_pipeline__quantity', 'num_pipeline__unit_price',
       'num_pipeline__discount', 'num_pipeline__delivery_days',
       'num_pipeline__customer_rating',
       'cat_pipeline__product_category_Beauty',
       'cat_pipeline__product_category_Clothing',
       'cat_pipeline__product_category_Electronics',
       'cat_pipeline__product_category_Home', 'cat_pipeline__region_East',
       'cat_pipeline__region_North', 'cat_pipeline__region_South',
       'cat_pipeline__region_West', 'cat_pipeline__payment_method_COD',
       'cat_pipeline__payment_method_Card',
       'cat_pipeline__payment_method_Wallet'], dtype=object)

In [70]:
df_transformed_pipeline = pd.DataFrame(df_transformed_pipeline, columns=column_names)
df_transformed_pipeline.head()

,num_pipeline__quantity,num_pipeline__unit_price,num_pipeline__discount,num_pipeline__delivery_days,num_pipeline__customer_rating,cat_pipeline__product_category_Beauty,cat_pipeline__product_category_Clothing,cat_pipeline__product_category_Electronics,cat_pipeline__product_category_Home,cat_pipeline__region_East,cat_pipeline__region_North,cat_pipeline__region_South,cat_pipeline__region_West,cat_pipeline__payment_method_COD,cat_pipeline__payment_method_Card,cat_pipeline__payment_method_Wallet
0,1.462828,0.385431,0.986412,1.230975,1.491025,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,1.462828,-1.540268,-0.887471,-0.037679,0.799944,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,-0.517177,0.016906,1.282289,-0.037679,-0.409448,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.472825,1.276578,-1.577850,-0.037679,-1.186914,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.472825,-0.995901,1.479540,-0.672006,1.663795,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0


**Task 8: Full Scikit-learn Pipeline**

1. Create a complete pipeline using scikit-learn pipeline library:
2. Raw Data → Encoding → Scaling → Model
3. Use any simple model:
   - LinearRegression OR
   - LogisticRegression
4. Split data into train-test sets.
5. Fit the pipeline on training data.
6. Make predictions on test data.
   ⚠️ Do not tune hyperparameters.

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [73]:
X = df[categorical_columns + numerical_columns]
y = df['revenue']

In [74]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4000, 8), (1000, 8), (4000,), (1000,))

In [75]:
pipeline = Pipeline([
    ('preprocessor', pipeline),
    ('model', LinearRegression())
])
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['quantity', 'unit_price',
                                                   'discount', 'delivery_days',
                                                   'customer_rating']),
                                                 ('cat_pipeline',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder())]),
                                                  ['product_category', 'region',
                                                   'payment_method'])])),
                ('model', LinearRegression())])

In [ ]:
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

0.8697661563632769

In [77]:
print("mse:", mean_squared_error(y_test, y_pred))
print("r2_score:", r2_score(y_test, y_pred))

mse: 87746.96396841179
r2_score: 0.8697661563632769

**Task 9: Pipeline Benefits (Conceptual)**
Write short answers:

1. Why pipelines are important in ML?
2. What problems do pipelines solve?
3. Difference between manual preprocessing vs pipeline-based preprocessing.

**Answers (Task 9)**

1. **Why pipelines are important?**  
   Mostly so you don’t mess up the order of steps. Like encode → scale → model all stay together. Also easier to reuse on train and test without doing everything again by hand.

2. **What problems do they solve?**  
   - forgetting to apply the same preprocessing on test data  
   - data leakage (like fitting scaler on whole data by mistake)  
   - messy code with too many manual transforms  
   - hard to reproduce the same steps later  

3. **Manual vs pipeline preprocessing**  
   Manual = you do get_dummies / scaling yourself cell by cell. It works but easy to forget a step or do train/test differently.  
   Pipeline = preprocessing + model in one object. `fit` on train, `predict` on test, and it handles the transforms for you. Felt cleaner after using it in Task 8, even though setting it up was a bit confusing at first.